Repository nbc-team-gumi/goodbite-main, pull requests merged in 2024-07, with the labels that each got.

#54 32 feat review 도메인 구현
  http/review.http
  src/main/java/com/sparta/goodbite/domain/review/dto/CreateReviewRequestDto.java
  src/main/java/com/sparta/goodbite/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/goodbite/domain/review/dto/UpdateReviewRequestDto.java
  src/main/java/com/sparta/goodbite/domain/review/dto/validation/constraint/RatingConstraint.java
  src/main/java/com/sparta/goodbite/domain/review/dto/validation/validator/RatingValidator.java
  src/main/java/com/sparta/goodbite/exception/GlobalExceptionHandler.java
Labels: bug, enhancement

#58 55 refactor dev 브랜치 병합
  http/customer.http
  http/owner.http
  http/waiting.http
  src/main/java/com/sparta/goodbite/auth/dto/LoginRequestDto.java
  src/main/java/com/sparta/goodbite/auth/dummy/UserCredentials.java
  src/main/java/com/sparta/goodbite/auth/security/EmailUserDetails.java
  src/main/java/com/sparta/goodbite/auth/security/EmailUserDetailsService.java
  src/main/java/com/sparta/goodbite/domain/customer/controller/CustomerController.java
  src/main/java/com/sparta/goodbite/domain/customer/dto/CustomerSignUpRequestDto.java
  src/main/java/com/sparta/goodbite/domain/owner/controller/OwnerController.java
  src/main/java/com/sparta/goodbite/domain/owner/dto/OwnerSignUpRequestDto.java
  src/main/java/com/sparta/goodbite/domain/waiting/controller/WaitingController.java
  src/main/java/com/sparta/goodbite/domain/waiting/entity/Waiting.java
  src/main/java/com/sparta/goodbite/domain/waiting/repository/WaitingRepository.java
  src/main/java/com/sparta/goodbite/domain/waiting/service/WaitingService.java
Labels: bug

#80 💯 test: http 테스트 수정
  http/auth.http
  http/customer.http
Labels: bug

#83 71 refactor 리뷰 도메인 인증인가 적용
  src/main/java/com/sparta/goodbite/auth/security/WebSecurityConfig.java
  src/main/java/com/sparta/goodbite/common/UserCredentials.java
  src/main/java/com/sparta/goodbite/domain/customer/repository/CustomerRepository.java
  src/main/java/com/sparta/goodbite/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/goodbite/domain/review/dto/CreateReviewRequestDto.java
  src/main/java/com/sparta/goodbite/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/goodbite/domain/review/entity/Review.java
  src/main/java/com/sparta/goodbite/domain/review/service/ReviewService.java
Labels: enhancement

#84 62 refactor 메뉴 도메인 인증인가 적용
  src/main/java/com/sparta/goodbite/auth/security/WebSecurityConfig.java
  src/main/java/com/sparta/goodbite/common/UserCredentials.java
  src/main/java/com/sparta/goodbite/domain/menu/controller/MenuController.java
  src/main/java/com/sparta/goodbite/domain/menu/dto/CreateMenuRequestDto.java
  src/main/java/com/sparta/goodbite/domain/menu/dto/MenuResponseDto.java
  src/main/java/com/sparta/goodbite/domain/menu/dto/UpdateMenuRequestDto.java
  src/main/java/com/sparta/goodbite/domain/menu/dto/validation/constraint/AtLeastOneFieldConstraint.java
  src/main/java/com/sparta/goodbite/domain/menu/dto/validation/validator/AtLeastOneFieldValidator.java
  src/main/java/com/sparta/goodbite/domain/menu/entity/Menu.java
  src/main/java/com/sparta/goodbite/domain/menu/service/MenuService.java
  src/main/java/com/sparta/goodbite/domain/owner/repository/OwnerRepository.java
  src/main/java/com/sparta/goodbite/domain/restaurant/repository/RestaurantRepository.java
Labels: enhancement

#90 63 refactor restaurant 도메인 인증인가 추가
  src/main/java/com/sparta/goodbite/domain/menu/repository/MenuRepository.java
  src/main/java/com/sparta/goodbite/domain/menu/service/MenuService.java
  src/main/java/com/sparta/goodbite/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/sparta/goodbite/domain/restaurant/service/RestaurantService.java
Labels: enhancement

#97 ✨ feat: Owner 가입 승인 여부 검증
  src/main/java/com/sparta/goodbite/auth/security/EmailUserDetailsService.java
Labels: enhancement

#101 ✨ feat: UnauthorizedException 클래스 추가
  src/main/java/com/sparta/goodbite/exception/auth/detail/UnauthorizedException.java
Labels: enhancement

#109 📋 docs: 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/-💄front-프론트-이슈-템플릿.md
Labels: enhancement

#126 121 refactor pathvariable로 customeridownerid인자를 받는 부분 제거
  http/customer.http
  http/owner.http
  src/main/java/com/sparta/goodbite/domain/customer/controller/CustomerController.java
  src/main/java/com/sparta/goodbite/domain/customer/service/CustomerService.java
  src/main/java/com/sparta/goodbite/domain/owner/controller/OwnerController.java
  src/main/java/com/sparta/goodbite/domain/owner/service/OwnerService.java
Labels: enhancement

#118 112 front waiting 상태 변경 코드 추가
  http/waiting.http
  src/main/java/com/sparta/goodbite/domain/waiting/entity/Waiting.java
  src/main/java/com/sparta/goodbite/domain/waiting/repository/WaitingRepository.java
  src/main/java/com/sparta/goodbite/domain/waiting/service/WaitingService.java
Labels: enhancement
