Repository nbc-team-gumi/goodbite-main, pull requests merged in 2024-08, with the labels that each got.

#134 ✨ feat: 사업자 자신의 restaurantId를 얻을 수 있는 API
  src/main/java/com/sparta/goodbite/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/sparta/goodbite/domain/restaurant/dto/RestaurantIdResponseDto.java
  src/main/java/com/sparta/goodbite/domain/restaurant/service/RestaurantService.java
Labels: enhancement

#140 ✨ feat: OperatingHour 단일 조회 기능 추가
  src/main/java/com/sparta/goodbite/domain/operatinghour/controller/OperatingHourController.java
  src/main/java/com/sparta/goodbite/domain/operatinghour/dto/OperatingHourResponseDto.java
  src/main/java/com/sparta/goodbite/domain/operatinghour/service/OperatingHourService.java
Labels: enhancement

#142 ✨ feat: 웨이팅 API 응답에 손님 정보 추가
  http/waiting.http
  src/main/java/com/sparta/goodbite/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/sparta/goodbite/domain/waiting/controller/WaitingController.java
  src/main/java/com/sparta/goodbite/domain/waiting/dto/WaitingResponseDto.java
  src/main/java/com/sparta/goodbite/domain/waiting/service/WaitingService.java
Labels: enhancement

#148 ✨ feat: 로그인 성공시 응답본문으로 메세지와 함께 인증객체의 Role전달
  src/main/java/com/sparta/goodbite/auth/dto/LoginSuccessResponseDto.java
  src/main/java/com/sparta/goodbite/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/goodbite/common/response/ResponseUtil.java
Labels: enhancement

#155 🩹 fix: application-test.yml ddl-auto 수정
  src/main/resources/application-test.yml
Labels: bug

#153 150 bug 고객 및 사장 수정 삭제시 캐스팅하는 레이어 변경이후 데이터베이스에 저장되지 않는 오류 해결
  src/main/java/com/sparta/goodbite/domain/customer/controller/CustomerController.java
  src/main/java/com/sparta/goodbite/domain/customer/service/CustomerService.java
  src/main/java/com/sparta/goodbite/domain/owner/controller/OwnerController.java
  src/main/java/com/sparta/goodbite/domain/owner/service/OwnerService.java
Labels: bug

#158 🩹 fix: 로그인/회원가입 인가 문제 수정
  src/main/java/com/sparta/goodbite/auth/security/JwtAuthorizationFilter.java
Labels: bug

#171 🩹 fix: CORS 이슈
  src/main/java/com/sparta/goodbite/auth/util/JwtConfig.java
  src/main/java/com/sparta/goodbite/auth/util/JwtUtil.java
Labels: bug

#174 🩹 fix: CORS 필터를 JwtAuthorization 필터 뒤에 명시
  Dockerfile
  src/main/java/com/sparta/goodbite/auth/security/WebSecurityConfig.java
Labels: bug

#184 178 bug 쿠키 대신 헤더를 사용하도록 수정
  .github/workflows/github-action.yml
  src/main/java/com/sparta/goodbite/auth/controller/AuthController.java
  src/main/java/com/sparta/goodbite/auth/security/CorsConfig.java
  src/main/java/com/sparta/goodbite/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/goodbite/auth/security/JwtAuthorizationFilter.java
  src/main/java/com/sparta/goodbite/auth/service/AuthService.java
  src/main/java/com/sparta/goodbite/auth/util/JwtUtil.java
  src/main/java/com/sparta/goodbite/domain/waiting/service/WaitingService.java
Labels: bug

#203 182 feat 예약 기능 추가
  http/reservation.http
  src/main/java/com/sparta/goodbite/common/UserCredentials.java
  src/main/java/com/sparta/goodbite/domain/customer/entity/Customer.java
  src/main/java/com/sparta/goodbite/domain/menu/dto/CreateMenuRequestDto.java
  src/main/java/com/sparta/goodbite/domain/menu/dto/MenuResponseDto.java
  src/main/java/com/sparta/goodbite/domain/menu/dto/UpdateMenuRequestDto.java
  src/main/java/com/sparta/goodbite/domain/menu/dto/validation/validator/AtLeastOneFieldValidator.java
  src/main/java/com/sparta/goodbite/domain/menu/entity/Menu.java
  src/main/java/com/sparta/goodbite/domain/operatinghour/dto/CreateOperatingHourRequestDto.java
  src/main/java/com/sparta/goodbite/domain/operatinghour/dto/OperatingHourResponseDto.java
  src/main/java/com/sparta/goodbite/domain/operatinghour/dto/validation/validator/LocalTimeFormatValidator.java
  src/main/java/com/sparta/goodbite/domain/operatinghour/entity/OperatingHour.java
  src/main/java/com/sparta/goodbite/domain/operatinghour/enums/DayOfWeek.java
  src/main/java/com/sparta/goodbite/domain/operatinghour/repository/OperatingHourRepository.java
  src/main/java/com/sparta/goodbite/domain/owner/entity/Owner.java
  src/main/java/com/sparta/goodbite/domain/reservation/config/SchedulingConfig.java
  src/main/java/com/sparta/goodbite/domain/reservation/controller/ReservationController.java
  src/main/java/com/sparta/goodbite/domain/reservation/dto/CreateReservationRequestDto.java
  src/main/java/com/sparta/goodbite/domain/reservation/dto/MenuItemDto.java
  src/main/java/com/sparta/goodbite/domain/reservation/dto/ReservationResponseDto.java
  src/main/java/com/sparta/goodbite/domain/reservation/dto/validation/constraint/LocalDateFormatConstraint.java
  src/main/java/com/sparta/goodbite/domain/reservation/dto/validation/constraint/ReservationDateConstraint.java
  src/main/java/com/sparta/goodbite/domain/reservation/dto/validation/constraint/ReservationTimeConstraint.java
  src/main/java/com/sparta/goodbite/domain/reservation/dto/validation/constraint/TimeIntervalConstraint.java
  src/main/java/com/sparta/goodbite/domain/reservation/dto/validation/validator/LocalDateFormatValidator.java
  src/main/java/com/sparta/goodbite/domain/reservation/dto/validation/validator/ReservationDateValidator.java
  src/main/java/com/sparta/goodbite/domain/reservation/dto/validation/validator/ReservationTimeValidator.java
  src/main/java/com/sparta/goodbite/domain/reservation/dto/validation/validator/TimeIntervalValidator.java
  src/main/java/com/sparta/goodbite/domain/reservation/entity/Reservation.java
  src/main/java/com/sparta/goodbite/domain/reservation/entity/ReservationMenu.java
  src/main/java/com/sparta/goodbite/domain/reservation/entity/ReservationStatus.java
  src/main/java/com/sparta/goodbite/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/goodbite/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/goodbite/domain/reservation/service/ReservationStatusSchedulingService.java
  src/main/java/com/sparta/goodbite/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/sparta/goodbite/domain/restaurant/dto/RestaurantRequestDto.java
  src/main/java/com/sparta/goodbite/domain/restaurant/dto/RestaurantResponseDto.java
  src/main/java/com/sparta/goodbite/domain/restaurant/entity/Restaurant.java
  src/main/resources/application.yml
Labels: enhancement

#222 195 feat 카카오 로그인 추가
  .github/workflows/github-action.yml
  Dockerfile
  src/main/java/com/sparta/goodbite/auth/controller/AuthController.java
  src/main/java/com/sparta/goodbite/auth/dto/KakaoUserResponseDto.java
  src/main/java/com/sparta/goodbite/auth/dto/LoginRequestDto.java
  src/main/java/com/sparta/goodbite/auth/security/WebSecurityConfig.java
  src/main/java/com/sparta/goodbite/auth/service/AuthService.java
  src/main/java/com/sparta/goodbite/common/AppConfig.java
  src/main/java/com/sparta/goodbite/common/UserCredentials.java
  src/main/java/com/sparta/goodbite/domain/customer/dto/CustomerSignupRequestDto.java
  src/main/java/com/sparta/goodbite/domain/customer/entity/Customer.java
  src/main/java/com/sparta/goodbite/domain/owner/dto/OwnerSignUpRequestDto.java
  src/main/java/com/sparta/goodbite/domain/owner/entity/Owner.java
  src/main/java/com/sparta/goodbite/domain/owner/repository/OwnerRepository.java
  src/main/java/com/sparta/goodbite/exception/customer/CustomerErrorCode.java
  src/main/java/com/sparta/goodbite/exception/customer/detail/DuplicateKakaoIdException.java
  src/main/java/com/sparta/goodbite/exception/owner/OwnerErrorCode.java
  src/main/java/com/sparta/goodbite/exception/owner/detail/DuplicateKakaoIdException.java
Labels: enhancement

#244 230 bug 사용자 인증 시 오류 수정
  src/main/java/com/sparta/goodbite/auth/security/EmailAuthenticationProvider.java
  src/main/java/com/sparta/goodbite/auth/security/EmailUserDetails.java
  src/main/java/com/sparta/goodbite/auth/security/EmailUserDetailsService.java
  src/main/java/com/sparta/goodbite/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/goodbite/auth/security/JwtAuthorizationFilter.java
  src/main/java/com/sparta/goodbite/auth/security/WebSecurityConfig.java
  src/main/java/com/sparta/goodbite/auth/util/JwtUtil.java
  src/main/java/com/sparta/goodbite/domain/customer/repository/CustomerRepository.java
  src/main/java/com/sparta/goodbite/domain/owner/repository/OwnerRepository.java
Labels: bug

#254 175 feat https 리디렉션
  .github/workflows/github-action.yml
  Dockerfile
  src/main/java/com/sparta/goodbite/auth/security/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: bug, enhancement

#263 ✨ feat: 안심번호 정규식 추가
  src/main/java/com/sparta/goodbite/domain/restaurant/dto/RestaurantRequestDto.java
Labels: enhancement
